#!/usr/bin/env bash

# ./helpers/add-corpora-dataset.sh FILE JSON_KEY RUST_STRUCT_KEY
# if 'JSON_KEY = lowercase filename' the key can be ommited
# RUST_STRUCT_KEY can be taken from the filename unless there's reason to specift something different.
# it should always be UPPERCASE.

echo "Creating backup"
cp src/data/corpora.rs src/data/corpora.rs.backup

echo "Adding data from files"

cat<<EOF > src/data/corpora.rs
/// Module corpora provides constants which contain the JSON in \`&str\` format to be consumed by the #
/// \`gen_corpora_switch\` function. Each JSON is taken from the [Corpora Project](https://github.com/dariusk/corpora)
/// and then cleaned-up to have only one filed named \`data\` which contains an array of strings.

// this file is generated by the ./helpers/corpora-data.sh script

EOF

# ANIMALS
./helpers/add-corpora-dataset.sh data/corpora/data/animals/cats.json
./helpers/add-corpora-dataset.sh data/corpora/data/animals/dinosaurs.json
./helpers/add-corpora-dataset.sh data/corpora/data/animals/dogs.json
./helpers/add-corpora-dataset.sh data/corpora/data/animals/donkeys.json
./helpers/add-corpora-dataset.sh data/corpora/data/animals/horses.json

# TV-SHOWS
./helpers/add-corpora-dataset.sh data/corpora/data/film-tv/tv_shows.json

# FOOD
./helpers/add-corpora-dataset.sh data/corpora/data/foods/fruits.json
./helpers/add-corpora-dataset.sh data/corpora/data/foods/pizzaToppings.json
./helpers/add-corpora-dataset.sh data/corpora/data/foods/herbs_n_spices.json herbs HERBS
./helpers/add-corpora-dataset.sh data/corpora/data/foods/herbs_n_spices.json spirces SPICES
./helpers/add-corpora-dataset.sh data/corpora/data/foods/herbs_n_spices.json mixtures MIXTURES
./helpers/add-corpora-dataset.sh data/corpora/data/foods/tea.json teas TEAS
./helpers/add-corpora-dataset.sh data/corpora/data/foods/vegetables.json

# GAMES
./helpers/add-corpora-dataset.sh data/corpora/data/games/rpg/rpg_games.json rpgs RPGS
./helpers/add-corpora-dataset.sh data/corpora/data/games/board_games.json
./helpers/add-corpora-dataset.sh data/corpora/data/games/wrestling_moves.json

# GEOGRAPHY
./helpers/add-corpora-dataset.sh data/corpora/data/geography/countries.json
./helpers/add-corpora-dataset.sh data/corpora/data/geography/nationalities.json

# GOVERNMENTS
./helpers/add-corpora-dataset.sh data/corpora/data/governments/governmentForms.json

# HUMANS
./helpers/add-corpora-dataset.sh data/corpora/data/humans/authors.json
./helpers/add-corpora-dataset.sh data/corpora/data/humans/bodyParts.json
./helpers/add-corpora-dataset.sh data/corpora/data/humans/firstNames.json
./helpers/add-corpora-dataset.sh data/corpora/data/humans/lastNames.json
./helpers/add-corpora-dataset.sh data/corpora/data/humans/moods.json
./helpers/add-corpora-dataset.sh data/corpora/data/humans/neutralNames.json
./helpers/add-corpora-dataset.sh data/corpora/data/humans/occupations.json
./helpers/add-corpora-dataset.sh data/corpora/data/humans/prefixes.json
./helpers/add-corpora-dataset.sh data/corpora/data/humans/scientists.json
./helpers/add-corpora-dataset.sh data/corpora/data/humans/suffixes.json
./helpers/add-corpora-dataset.sh data/corpora/data/humans/tolkienCharacterNames.json names TOLKIEN_CHARACTER_NAMES

# MATERIALS
./helpers/add-corpora-dataset.sh data/corpora/data/materials/fabrics.json
./helpers/add-corpora-dataset.sh data/corpora/data/materials/gemstones.json
./helpers/add-corpora-dataset.sh data/corpora/data/materials/metals.json
./helpers/add-corpora-dataset.sh data/corpora/data/materials/packaging.json

# MUSIC
./helpers/add-corpora-dataset.sh data/corpora/data/music/genres.json genres MUSIC_GENRES

# OBJECTS
./helpers/add-corpora-dataset.sh data/corpora/data/objects/objects.json

# PLANTS
./helpers/add-corpora-dataset.sh data/corpora/data/plants/flowers.json
./helpers/add-corpora-dataset.sh data/corpora/data/plants/toxic_plants.json plants TOXIC_PLANTS

# SCIENCE
./helpers/add-corpora-dataset.sh data/corpora/data/science/weather_conditions.json conditions

# SPORTS
./helpers/add-corpora-dataset.sh data/corpora/data/sports/sports.json

# TECHNOLOGY
./helpers/add-corpora-dataset.sh data/corpora/data/technology/appliances.json
./helpers/add-corpora-dataset.sh data/corpora/data/technology/new_technologies.json
./helpers/add-corpora-dataset.sh data/corpora/data/technology/programming_languages_popular.json programming_languages_popular PROGRAMMING_LANGUAGES


echo "Done."
echo "NEW data sources"

grep "pub const" src/data/corpora.rs | awk -F':' '{ print $1 }' | awk -F ' ' '{ print "\""tolower(substr($3,6))"\" => corpora::"$3"," }'

echo ""
echo "Add these to get_dataset in src/data.rs"
